self hosted runner

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -62,7 +62,7 @@ test:
       junit: unit-test-results.xml
   rules:
     - if: '$CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_TAG' # Check if it's master or a tag
-      allow_failure: false # Allow this job to fail without failing the pipeline
+      allow_failure: false              # Allow this job to fail without failing the pipeline if it's not on master or a tag
 
 
 
@@ -111,16 +111,17 @@ docker_image_build_push:
     - |
       #! /bin/bash
       echo "Login into $DOCKER_REGISTRY registry..."
+      docker logout || echo "docker logout failed"
       mkdir -p ~/.docker
       echo '{"auths":{"https://index.docker.io/v1/":{"auth":"'$DOCKERHUB_AUTH'"}}}' > ~/.docker/config.json
-      docker login
+      docker login || echo "docker login failed"
 
   script:
     - echo "DOCKERHUB_USERNAME/APP_NAME:IMAGE_TAG=$DOCKERHUB_USERNAME/$APP_NAME:$IMAGE_TAG"
     - docker build . -t $DOCKERHUB_USERNAME/$APP_NAME:$IMAGE_TAG
     - echo "docker build is completed..!! $DOCKERHUB_USERNAME/$APP_NAME:$IMAGE_TAG"
 
-    - docker images
+    - docker image ls
 
     - echo "Pushing to docker registry..."
     - docker push $DOCKERHUB_USERNAME/$APP_NAME:$IMAGE_TAG
@@ -165,7 +166,7 @@ docker_image_build_push:
 helm_lint_template:
   stage: helm_kube_deploy
   needs: [docker_image_build_push, docker_image_tag, set_env_variables]
-  image: alpine/k8s:1.31.1
+  image: alpine/k8s:1.32.5
 
   script:
     - helm lint ./helm
@@ -174,10 +175,8 @@ helm_lint_template:
 helm_kube_deploy:
   stage: helm_kube_deploy
   needs: [docker_image_build_push, helm_lint_template, docker_image_tag, set_env_variables]
-  image: ubuntu:24.04
+  image: alpine/k8s:1.32.5
   before_script:
-    - *setup_tailscale
-    - *setup_helm_and_kubectl
     - |
       #! /bin/bash
       mkdir -p ~/.kube && touch ~/.kube/config
@@ -187,3 +186,21 @@ helm_kube_deploy:
   script: |
     echo "helm upgrade --install $APP_NAME-$CI_COMMIT_REF_NAME ./helm --set image.tag=$IMAGE_TAG"
     helm upgrade --install "${APP_NAME}-${CI_COMMIT_REF_NAME}" ./helm --set image.tag=$IMAGE_TAG
+
+
+# helm_kube_deploy:
+#   stage: helm_kube_deploy
+#   needs: [docker_image_build_push, helm_lint_template, docker_image_tag, set_env_variables]
+#   image: ubuntu:24.04
+#   before_script:
+#     - *setup_tailscale
+#     - *setup_helm_and_kubectl
+#     - |
+#       #! /bin/bash
+#       mkdir -p ~/.kube && touch ~/.kube/config
+#       echo "${KUBE_CONFIG}" | base64 --decode > ~/.kube/config
+#       chmod 600 ~/.kube/config
+#       kubectl get all --all-namespaces
+#   script: |
+#     echo "helm upgrade --install $APP_NAME-$CI_COMMIT_REF_NAME ./helm --set image.tag=$IMAGE_TAG"
+#     helm upgrade --install "${APP_NAME}-${CI_COMMIT_REF_NAME}" ./helm --set image.tag=$IMAGE_TAG
